version: '3.8'

services:
  app:
    # Use your existing Dockerfile to build the image
     image: node:16  # Use the official Node.js image from Docker Hub
    
    build:
    
     # Set working directory for the application
    working_dir: /usr/src/app

    # Expose port 5174 so that the host can access the app
    ports:
      - "5174:5174"
   
    # Set the default command to run the app
    command: npm run dev
    # Enable container to restart on failure
    restart: on-failure
